In [16]:
import numpy as np
import pandas as pd


train_data = pd.DataFrame({
    "Age": [20, 21, 22, 20, 23, 21, 22, np.nan, 19, 25],
    
    "Study_Hours": [
        5, 6, 4, np.nan, 7,
        5, 6, 4, 10, 5
    ],
    
    "Gender": [
        "Male", "Female", "Male", "Female", "Male",
        "Female", np.nan, "Male", "Female", "Male"
    ],

    
})

print(train_data)

#  numerical column   => Age, study hour  =   simpleimputer(strategy="mean")  =>  meanmaxscaler()
#  categorical column  => gender  =   simpleimputer(strategy="most_frequent")  =>  onehotencoder

    Age  Study_Hours  Gender
0  20.0          5.0    Male
1  21.0          6.0  Female
2  22.0          4.0    Male
3  20.0          NaN  Female
4  23.0          7.0    Male
5  21.0          5.0  Female
6  22.0          6.0     NaN
7   NaN          4.0    Male
8  19.0         10.0  Female
9  25.0          5.0    Male

In [17]:
numerical_feature =  train_data.select_dtypes(include=["int64", "float64"]).columns#["Age","Study_Hours"]
categorical_feature = train_data.select_dtypes(include=["str"]).columns#["Gender"]

In [18]:


from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder

numerical_pipeline= Pipeline(#first simpleImputer will work then min  min max scaaler will work
    [
        ("imputer", SimpleImputer(strategy="mean")),
        ("minmaxscaling", MinMaxScaler())
    ]
)

categorical_pipeline = Pipeline(
    [
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("ohe", OneHotEncoder())
    ]
)



preprocessor=   ColumnTransformer(#
    [
        ("numercial", numerical_pipeline, numerical_feature),#["Age","Study_Hours"]
        ("categorical", categorical_pipeline, categorical_feature)#["Gender"]
    ],
    verbose_feature_names_out=False
)

In [21]:
all_featrues  =  preprocessor.fit_transform(train_data)
train_data[preprocessor.get_feature_names_out()] = all_featrues
train_data

        Age  Study_Hours  Gender  Gender_Female  Gender_Male
0  0.166667     0.166667    Male            0.0          1.0
1  0.333333     0.333333  Female            1.0          0.0
2  0.500000     0.000000    Male            0.0          1.0
3  0.166667     0.296296  Female            1.0          0.0
4  0.666667     0.500000    Male            0.0          1.0
5  0.333333     0.166667  Female            1.0          0.0
6  0.500000     0.333333     NaN            0.0          1.0
7  0.407407     0.000000    Male            0.0          1.0
8  0.000000     1.000000  Female            1.0          0.0
9  1.000000     0.166667    Male            0.0          1.0

In [22]:
test_data = pd.DataFrame({
    "Age": [22, np.nan, 24],
    
    "Study_Hours": [6, 3, np.nan],
    
    "Gender": ["Female", np.nan, "Female"],
    
})

print(test_data)

    Age  Study_Hours  Gender
0  22.0          6.0  Female
1   NaN          3.0     NaN
2  24.0          NaN  Female

In [23]:
test_featrues = preprocessor.transform(test_data)
test_data[preprocessor.get_feature_names_out()] = test_featrues
test_data

         Age  Study_Hours  Gender  Gender_Female  Gender_Male
0  22.000000     6.000000  Female            1.0          0.0
1   0.407407     3.000000     NaN            0.0          1.0
2  24.000000     0.296296  Female            1.0          0.0