In [ ]:
import pandas as pd
import numpy as np
from  sklearn.pipeline  import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

train_data = pd.DataFrame({
    "Age": [20, 21, 22, 20, 23, 21, 22, 24, 19, 25],
    
    "Study_Hours": [
        5, 6, 4, np.nan, 7,
        5, 6, 4, 10, 5
    ],
    
    "Gender": [
        "Male", "Female", "Male", "Female", "Male",
        "Female", np.nan, "Male", "Female", "Male"
    ],
    "Result":[1,0,1,0,1,0,1,1,0,1]
    
})

print(train_data)

   Age  Study_Hours  Gender  Result
0   20          5.0    Male       1
1   21          6.0  Female       0
2   22          4.0    Male       1
3   20          NaN  Female       0
4   23          7.0    Male       1
5   21          5.0  Female       0
6   22          6.0     NaN       1
7   24          4.0    Male       1
8   19         10.0  Female       0
9   25          5.0    Male       1

In [ ]:
test_data = pd.DataFrame({
    "Age": [22, np.nan, 24],
    
    "Study_Hours": [6, 3, np.nan],
    
    "Gender": ["Female", "Male", "Female"],
    "Result":[1,0,1]
    
})

print(test_data)

    Age  Study_Hours  Gender  Result
0  22.0          6.0  Female       1
1   NaN          3.0    Male       0
2  24.0          NaN  Female       1

In [289]:
# make pipeline form train data and  implement that pipeline on a dest dat 
# fill numerical value by median
# fill categorical value by most_frequent
#encode categorical value by one hot encoding

In [290]:
num_col = train_data.select_dtypes(include=["int64", "float64"]).columns
cat_col = train_data.select_dtypes(include=["str"]).columns

In [ ]:
#numerical pipeline 

num_pipeline = Pipeline(
    [
        ("imputer", SimpleImputer(strategy="mean"))

    ]
)

In [292]:
#categorical pipeline 
cat_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(drop="first"))
])

In [293]:
#combine pipelein 

pipeline = ColumnTransformer(
    [
        ("numerical", num_pipeline,num_col),
        ("categorical", cat_pipeline,cat_col)
    ],
     verbose_feature_names_out=False # it does not change column name
)

In [294]:
pipeline.fit_transform(train_data)  #here note though it congain Result which is not part of ColumnTransformer , it will work
# pipeline.fit_transform(train_data[["Age", "Study_Hours", "Gender"]])
# pipeline.fit_transform(train_data[["Gender", "Age", "Study_Hours"]])#we can chage column order
# pipeline.fit_transform(train_data[["Age","Gender" ]])# error we can chage column order but all column used by ColumnTransforme must be present
# pipeline.fit_transform(train_data[["Age","Gender" ]])# error we can chage column order but all column used by ColumnTransforme must be present

array([[20.        ,  5.        ,  1.        ,  1.        ],
       [21.        ,  6.        ,  0.        ,  0.        ],
       [22.        ,  4.        ,  1.        ,  1.        ],
       [20.        ,  5.77777778,  0.        ,  0.        ],
       [23.        ,  7.        ,  1.        ,  1.        ],
       [21.        ,  5.        ,  0.        ,  0.        ],
       [22.        ,  6.        ,  1.        ,  1.        ],
       [24.        ,  4.        ,  1.        ,  1.        ],
       [19.        , 10.        ,  0.        ,  0.        ],
       [25.        ,  5.        ,  1.        ,  1.        ]])

In [295]:
print(pipeline.get_feature_names_out())

['Age' 'Study_Hours' 'Result' 'Gender_Male']

In [296]:
train_data[pipeline.get_feature_names_out()]  =pipeline.fit_transform(train_data)

In [297]:
train_data

    Age  Study_Hours  Gender  Result  Gender_Male
0  20.0     5.000000    Male     1.0          1.0
1  21.0     6.000000  Female     0.0          0.0
2  22.0     4.000000    Male     1.0          1.0
3  20.0     5.777778  Female     0.0          0.0
4  23.0     7.000000    Male     1.0          1.0
5  21.0     5.000000  Female     0.0          0.0
6  22.0     6.000000     NaN     1.0          1.0
7  24.0     4.000000    Male     1.0          1.0
8  19.0    10.000000  Female     0.0          0.0
9  25.0     5.000000    Male     1.0          1.0

In [298]:
#now for test data  us transform
#it fill median of train data in test data
test_data[pipeline.get_feature_names_out()]  =pipeline.transform(test_data)
test_data

    Age  Study_Hours  Gender  Result  Gender_Male
0  22.0     6.000000  Female     1.0          0.0
1  21.7     3.000000    Male     0.0          1.0
2  24.0     5.777778  Female     1.0          0.0