In [161]:

import pandas as pd

#methode to prevent from overfitting
## Generally overfit model has Coefficients(slope coeffient not constant) unnecessarily large, it means small change in input feature may result high prediction
## lasso and rigre regression  Both add a penalty for large coefficients:
## lasso and ridge regression shrink coefficient to reduce overfitting
##lasso => l1 regularization it add   alpha*|sum of coeffiecient| in cost funtion(mean square error) ie mse+alpha * sum of slope coeffiecint
##ridge => l2 regularization it add  alpha*(sum of square of coefficient) it is named l2 because it is square(2)

## (intercept/constant) is normally not included in the Lasso penalty.

Higher alpha→stronger penalty→more coefficient shrinking
if you increase to much alpha => slop will be very less it means output is less depend on input it result underfit
	​


and

Lower alpha→weaker penalty→less coefficient shrinking
	​

In [162]:
df=pd.read_csv("./dataset/house.csv")

In [163]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [164]:
#checking null value
df.isnull().sum().sum()

np.int64(0)

In [165]:

X = df.drop(columns=["price"])
y=df["price"]

In [166]:

X = df.drop(columns=["price"])
y=df["price"]
#splitting data in train test
from sklearn.model_selection  import train_test_split
X_train, X_test, y_train,y_test=train_test_split(X,y, test_size=0.2, random_state=2)
y_train

412    3430000
284    4270000
504    2653000
209    4900000
269    4375000
        ...
299    4200000
534    2100000
493    2800000
527    2275000
168    5250000
Name: price, Length: 436, dtype: int64

In [167]:
#making pipeline
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression

In [168]:
#categorical columns  and numerical columns
df_categorical_columns = X.select_dtypes(include=["object"]).columns
df_numerical_columns = X.select_dtypes(include=["int64","float64"]).columns
df_categorical_columns

C:\Users\acer\AppData\Local\Temp\ipykernel_23784\3383917996.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df_categorical_columns = X.select_dtypes(include=["object"]).columns

Index(['mainroad', 'guestroom', 'basement', 'hotwaterheating',
       'airconditioning', 'prefarea', 'furnishingstatus'],
      dtype='str')

In [169]:
preprocessor = ColumnTransformer([
    ("num",StandardScaler(), df_numerical_columns), #if you dont do standardScaler you can see r2 score will highly drop
    ("cat",OneHotEncoder(),df_categorical_columns )
])

In [170]:
#creating pipelin
from sklearn.linear_model import Lasso,Ridge
pipeline = Pipeline([
    ("preprocessor",preprocessor), #it takes input features
   ("model",LinearRegression()) 
    # ("model", Lasso(alpha=1))#you can tune to alpha to what ever value
      # ("model",Ridge(alpha=1))#you can tune alpha to what ever value
])

In [171]:
#training the model
pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['area', 'bedrooms', 'bathrooms', 'stories', 'parking'], dtype='str')),
                                                 ('cat', OneHotEncoder(),
                                                  Index(['mainroad', 'guestroom', 'basement', 'hotwaterheating',
       'airconditioning', 'prefarea', 'furnishingstatus'],
      dtype='str'))])),
                ('model', LinearRegression())])

In [172]:
#r2 score
print("training accuracy", pipeline.score(X_train,y_train))
print("testing accuracy", pipeline.score(X_test,y_test))
# print("intercept", pipeline.named_steps["model"].intercept_)
# print("coefficients", pipeline.named_steps["model"].coef_)

training accuracy 0.6918324307049804
testing accuracy 0.6298518608872241

In [173]:
#saving the model using joblib package
#using joblib we can save
#model, dataframe
#in google colab it is recommend that once you dump downoad it and store in local computer, in another session , data will be deleted automateically
import joblib
joblib.dump(pipeline,"house_price_prediction.joblib")#or use .pkl
joblib.dump(pipeline,"house_price_prediction.pkl")#or use .pkl

['house_price_prediction.pkl']

In [174]:
X_test

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
333,3000,3,1,2,yes,no,no,no,no,0,no,semi-furnished
84,3760,3,1,2,yes,no,no,yes,no,2,no,semi-furnished
439,3930,2,1,1,no,no,no,no,no,0,no,unfurnished
396,3640,2,1,1,yes,no,no,no,no,1,no,semi-furnished
161,6100,3,1,3,yes,yes,no,no,yes,0,yes,semi-furnished
...,...,...,...,...,...,...,...,...,...,...,...,...
100,6600,3,2,1,yes,no,yes,no,yes,0,yes,unfurnished
344,3850,2,1,1,yes,no,no,no,no,0,no,semi-furnished
176,8520,3,1,1,yes,no,no,no,yes,2,no,furnished
244,5320,3,1,2,yes,yes,yes,no,no,0,yes,semi-furnished
15,6000,4,1,2,yes,no,yes,no,no,2,no,semi-furnished

In [175]:
#saving X_test
# joblib.dump(X_test, "X_test.joblib")